### ISSUE TITLE
scale support

### ISSUE THREAD

**Issue by rickytan** [mattt/WebPImageSerialization#13]
Hi, I think this [line](https://github.com/mattt/WebPImageSerialization/blob/master/WebPImageSerialization/WebPImageSerialization.m#L114) should be:

``` objective-c
        UIImage *image = [UIImage imageWithCGImage:imageRef
                                             scale:scale
                                       orientation:UIImageOrientationUp];
```

**Comment by mattt** [comment]
You're absolutely correct. Thanks for pointing this out, @rickytan. This is fixed in fad66d7.
