### ISSUE TITLE
imageWithContentsOfFile retina images

### ISSUE THREAD

**Issue by CraigMason** [mattt/WebPImageSerialization#8]
Is there any way to load in retina images when using `imageWithContentsOfFile` ? `UIImage` will normally check if the @2x version for the requested file is available and use that instead.

Attempting to do this with webp images only loads the standard form. Supplying the @2x image path directly isn't suitable as the `UIImage` scale will still be 1.0 (unless set manually).

Thanks

**Comment by mattt** [comment]
Sorry for the late response, @CraigMason. This is now fixed by aa17cb3.
